name: Copy Docker Image Tag
run-name: Copy ${{ inputs.source_repo }} to ${{ inputs.destination_repo }}
on: 
  workflow_dispatch:
    inputs:
      source:
        description: '来源仓库 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标仓库 (Registry)'
        required: true
        default: 'registry.cn-hangzhou.aliyuncs.com'
      source_repo:
        description: '来源镜像及标签 (格式 repo:tag)'
        required: true
        default: 'liuxy0551/yice-server:amd64'
      destination_repo:
        description: '目标镜像及标签 (格式 repo:tag)'
        required: true
        default: 'liuxy0551/yice-server:amd64'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Docker Image Tag
      uses: ikrong/docker-sync-action@main
      with:
        source: ${{ github.event.inputs.source }}
        source-credential: ${{ secrets.SOURCE_CREDENTIAL }}
        destination: ${{ github.event.inputs.destination }}
        destination-credential: ${{ secrets.DESTINATION_CREDENTIAL }}
        copy: "${{ github.event.inputs.source_repo }} ${{ github.event.inputs.destination_repo }}"
